remote_theme: Stwissel/just-the-docs
title: "Samsara"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github01.hclpnp.com/HCL-Janus/samsara" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

exclude:
  [
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfle.lock"
  ]

# Back to top link
back_to_top: false
back_to_top_text: "Back to top"

next_page: true

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
